# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='asientos_contables',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.Estado'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.Estado'),
        ),
        migrations.AlterField(
            model_name='tipos_documentos',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.Estado'),
        ),
    ]
