# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0002_auto_20170713_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipos_Movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='asientos_contables',
            name='Tipo_Movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.Tipos_Movimientos'),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='Tipo_Movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.Tipos_Movimientos'),
        ),
    ]
