# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0005_auto_20170726_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientos_contables',
            name='Cuenta',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Cedula',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Limite_Credito',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
